name: Sync with Upstream

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Allows manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream remote
        run: git remote add upstream https://github.com/athena-codes/a-A-summer-hackathon.git

      - name: Fetch upstream
        run: git fetch upstream

      - name: Merge upstream/main into main
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes to main branch
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
